name: tsmorph
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy=1.22.4
  - scipy=1.8.1                    
  - pip
  - pip:
    - neuralforecast
    - pycatch22
    - pandas
    - scikit-learn
    - matplotlib

