name: tsmorph
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy                
  - pip
  - pip:
    - neuralforecast
    - pycatch22
    - pandas
    - scikit-learn
    - matplotlib
    - sktime
    - psutil

