name: tsmorph
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy=1.22.4
  - pandas=1.5.1
  - matplotlib=3.6.2
  - scipy=1.8.1                    
  - scikit-learn=1.1.3
  - sktime=0.14.0
  - pip
  - pip:
    - darts==0.23.1 
    - tsfel==0.1.4 
