name: tsmorph
channels:
  - defaults
  - 
dependencies:
  - python=3.8
  - numpy=1.22.4
  - pandas=1.5.1
  - matplotlib=3.6.2
  - scipy=1.8.1                    
  - scikit-learn=1.1.3
  - pip
  - pip:
    - neuralforecast
    - pycatch22

